Retry docker build and cosign actions (#9)

diff --git a/build-and-sign-image/action.yml b/build-and-sign-image/action.yml
--- a/build-and-sign-image/action.yml
+++ b/build-and-sign-image/action.yml
@@ -151,30 +151,32 @@ runs:
           ${{ steps.version.outputs.protect_version_tag_latest }}
 
     - name: 'Docker build and push protect-${{ inputs.component }}'
-      uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
+      uses: Wandalen/wretry.action@e68c23e6309f2871ca8ae4763e7629b9c258e1ea # v3.8.0
       id: push
       with:
-        # Without setting the context, the docker action will internally
-        # re-clone the repo from the Actions ref.
-        # We don't want that, as it's both not necessary
-        # (we should always run the checkout action explicitly before this),
-        # and we want preceding Cargo.toml version munges to be respected.
-        context: .
-        file: |
-              ${{
-                hashFiles(format('./images/Dockerfile.{0}', inputs.component)) != ''
-                && format('./images/Dockerfile.{0}', inputs.component)
-                || format('./images/Containerfile.{0}', inputs.component)
-              }}
-        platforms: linux/amd64
-        tags: '${{ steps.meta.outputs.tags }}'
-        push: '${{ inputs.push }}'
-        # TODO: Handle in-container script auth better
-        build-args: |
-          PROTECT_VERSION=${{ steps.version.outputs.protect_version }}
-          REGISTRY_USER=oauth2accesstoken
-        secrets: |
-          registry_token=${{ steps.google-auth.outputs.access_token }}
+        action: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
+        with: |
+          # Without setting the context, the docker action will internally
+          # re-clone the repo from the Actions ref.
+          # We don't want that, as it's both not necessary
+          # (we should always run the checkout action explicitly before this),
+          # and we want preceding Cargo.toml version munges to be respected.
+          context: .
+          file: ${{
+            hashFiles(format('./images/Dockerfile.{0}', inputs.component)) != ''
+            && format('./images/Dockerfile.{0}', inputs.component)
+            || format('./images/Containerfile.{0}', inputs.component)
+          }}
+          platforms: linux/amd64
+          tags: ${{ steps.meta.outputs.tags }}
+          push: ${{ inputs.push }}
+          build-args: |
+            PROTECT_VERSION=${{ steps.version.outputs.protect_version }}
+            REGISTRY_USER=oauth2accesstoken
+          secrets: |
+            registry_token=${{ steps.google-auth.outputs.access_token }}
+        attempt_limit: 3
+        attempt_delay: 30000
 
     - name: 'Cosign sign all images'
       if: '${{ inputs.push == true }}'
@@ -183,7 +185,12 @@ runs:
         for tag in $(echo '${{ steps.meta.outputs.tags }}'); do
           pullstring="${tag}@${DIGEST}"
           echo "Signing ${pullstring}"
-          cosign sign --yes "${pullstring}"
+          for i in $(seq 1 5); do
+            cosign sign --yes "${pullstring}" && break
+            echo "Attempt $i failed for ${pullstring}, retrying in 15s..."
+            sleep 15
+            [ $i -eq 5 ] && exit 1
+          done
         done
       env:
         DIGEST: '${{ steps.push.outputs.digest }}'
